---
title: "Join our group!"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

\large

**Placements / Projects**

Please get in touch for placements/project work, applications are always welcome. Minimum duration 4-6 weeks. Funding possible.

- pupils
- Bachelor
- Master
- visiting scientists (PhD, Post-doc)

**Bachelor and Master theses projects**

We take Bachelor students (internal and external) on ecological, molecular biology and computational biology projects. International students welcome. Funding possible.

- Field site projects in Teutoburger forest on great and blue tits
- Next-gen and third-gen sequencing approaches
- Fur seal genomics
- Epigenetics

**PhD**

Please enquire about PhD options in our lab! [We are looking for 2 PhD students to join our lab](files/PHD-AD1.pdf)! We support National and International applications.


**Post-doc**

Please enquire about Post-doc options in our lab! [We are currently looking for a Postdoc in computational population genetics](files/Postdoc-AD1.pdf). We support National and International applications.